version: '3'
services:
  frontend:
    build: .
    image: awahab07/popular-repos-github
    command: yarn run start
    volumes:
      - .:/app
    ports:
      - 3333:3000

  e2e:
    image: "cypress/included:4.1.0"
    command: "--browser chrome"
    depends_on:
      - frontend
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json

  e2e-firefox:
    image: "cypress/included:4.1.0"
    command: "--browser firefox --config video=false"
    depends_on:
      - frontend
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
